from django.conf import settings

DOWNLOAD_PATH = settings.get("WAGTAIL_CLIP_DOWNLOAD_PATH", "/clip")
SEARCH_BACKEND_NAME = settings.get("WAGTAIL_CLIP_SEARCH_BACKEND_NAME", "clip")
MAX_IMAGE_SEARCH_RESULTS = settings.get("WAGTAIL_CLIP_MAX_IMAGE_SEARCH_RESULTS", 256)
